TARGET_DIRECTORY = "target/"
JSON_EXPORT_FILE = TARGET_DIRECTORY + "json_publication.js"
COPY_FLAGS_TO_DIRECTORY = TARGET_DIRECTORY + "flags/"
COPY_CLASS_IMAGES_TO_DIRECTORY = TARGET_DIRECTORY + "class_images/"
